<a href="https://colab.research.google.com/github/Nathiskar/ML_Study/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantage of Numpy Arrays
  1. Allows several Mathematical Operations
  2. Faster Operations

In [1]:
import numpy as np

list Vs numpy - time Taken

In [2]:
from time import process_time

Time taken by a list

In [4]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.001488492000000008


In [6]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5 #np_array + 5

end_time = process_time()

print(end_time - start_time)

0.0013782500000001363


NumPy Arrays

In [7]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [8]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [9]:
# creating one dimensional array
a = np.array([1,2,3,5,6])
print(a)

[1 2 3 5 6]


In [10]:
a.shape # give the number of rows and coulmn

(5,)

In [11]:
# two dimensional array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
b.shape

(2, 4)

In [14]:
c = np.array([(1,2,3,4,5),(6,7,8,9,10)], dtype = float) #to create an array with floating points
print(c)
c.shape

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


(2, 5)

Intial Placeholders in numpy arrays

In [15]:
#create a numpy arrays of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
#create a numpy arrays of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
#create a numpy arrays of any Value
z = np.full((5,4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [19]:
# create an indentity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
#create a numpy array with random numbers
b = np.random.random((3,4))
print(b)

[[0.85619093 0.26798038 0.48038775 0.24756667]
 [0.07691782 0.09009516 0.52014903 0.36949566]
 [0.26925368 0.69478498 0.11539488 0.38501788]]


In [22]:
# random value array - int within specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[33 54 65 86 92]
 [32 76 97 88 29]
 [76 32 30 59 98]]


In [23]:
#create an array with evenly space values ---> specifiing the number of values needed
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [25]:
#create an array with  evenly space values specifing the steps
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [27]:
#convert a list to a numpy array
list2 = [10, 20, 20, 50, 20]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 50 20]


numpy.ndarray

Analysising a numpy array

In [29]:
c = np.random.randint(10,90,(5,5))
print(c)

[[45 15 36 58 20]
 [20 18 59 81 30]
 [45 44 56 46 25]
 [22 17 58 72 61]
 [79 27 62 69 37]]


In [30]:
c.shape

(5, 5)

In [31]:
#number of dimensions
print(c.ndim)

2


In [32]:
#number of elements in an array
print(c.size)

25


In [33]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical Operations on a np array

In [34]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatenate or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [36]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,20,(3,3))

print(a)
print(b)

[[2 2 1]
 [6 0 6]
 [2 1 5]]
[[ 2 11 13]
 [ 4 10  9]
 [10 10 11]]


In [37]:
print(a+b) # element wise addition

[[ 4 13 14]
 [10 10 15]
 [12 11 16]]


In [38]:
print(a-b)

[[  0  -9 -12]
 [  2 -10  -3]
 [ -8  -9  -6]]


In [39]:
print(a*b)

[[ 4 22 13]
 [24  0 54]
 [20 10 55]]


In [40]:
print(a/b)

[[1.         0.18181818 0.07692308]
 [1.5        0.         0.66666667]
 [0.2        0.1        0.45454545]]


In [41]:
# another way to do mathematical operations
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,20,(3,3))

print(a)
print(b)

[[9 2 9]
 [8 4 2]
 [1 9 8]]
[[ 5  8 12]
 [ 5  8  2]
 [10  8  4]]


In [42]:
print(np.add(a,b))

[[14 10 21]
 [13 12  4]
 [11 17 12]]


In [43]:
print(np.subtract(a,b))

[[ 4 -6 -3]
 [ 3 -4  0]
 [-9  1  4]]


In [44]:
print(np.multiply(a,b))

[[ 45  16 108]
 [ 40  32   4]
 [ 10  72  32]]


In [45]:
print(np.divide(a,b))

[[1.8   0.25  0.75 ]
 [1.6   0.5   1.   ]
 [0.1   1.125 2.   ]]


Array Manipulation

In [47]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 3 4]
 [0 9 3]]
(2, 3)


In [49]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[0 0]
 [3 9]
 [4 3]]
(3, 2)


In [50]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 5 5]
 [0 3 2]]
(2, 3)


In [51]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[0 0]
 [5 3]
 [5 2]]
(3, 2)


In [52]:
# reshaping the array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 2 9]
 [5 4 0]]
(2, 3)


In [53]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[2 2]
 [9 5]
 [4 0]]
(3, 2)
